<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-24V1VQ8" failures="1" tests="10" name="com.sgtesting.prototype.AssignmentPrototype5" time="61.636" errors="0" timestamp="2023-03-31T08:07:19 IST" skipped="0">
  <testcase classname="com.sgtesting.prototype.AssignmentPrototype5" name="launchbrowser" time="1.468"/>
  <system-out/>
  <testcase classname="com.sgtesting.prototype.AssignmentPrototype5" name="Navigate" time="2.938"/>
  <system-out/>
  <testcase classname="com.sgtesting.prototype.AssignmentPrototype5" name="adminLogin" time="8.519"/>
  <system-out/>
  <testcase classname="com.sgtesting.prototype.AssignmentPrototype5" name="Minimize" time="2.391"/>
  <system-out/>
  <testcase classname="com.sgtesting.prototype.AssignmentPrototype5" name="createuser" time="11.213">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.sgtesting.prototype.AssignmentPrototype5.createuser(AssignmentPrototype5.java:108)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createuser -->
  <system-out/>
  <testcase classname="com.sgtesting.prototype.AssignmentPrototype5" name="createuser" time="11.084"/>
  <system-out/>
  <testcase classname="com.sgtesting.prototype.AssignmentPrototype5" name="createuser" time="12.524"/>
  <system-out/>
  <testcase classname="com.sgtesting.prototype.AssignmentPrototype5" name="deleteuser" time="8.663"/>
  <system-out/>
  <testcase classname="com.sgtesting.prototype.AssignmentPrototype5" name="Logout" time="2.533"/>
  <system-out/>
  <testcase classname="com.sgtesting.prototype.AssignmentPrototype5" name="CloseAppln" time="0.303"/>
  <system-out/>
</testsuite> <!-- com.sgtesting.prototype.AssignmentPrototype5 -->
